#!/bin/bash

# Prepare Android files for Weblate
langs=$(egrep '=' data/strings/strings.txt | cut -d "=" -f1 | sed "s/[[:space:]]//g" | egrep -v "comment|tags|ref" | cut -d ":" -f 1 | sort -u)
android_strings_xml=$(find android/app/src/main/res/values* -name "strings.xml" -type f)
iphone_strings=$(find iphone/Maps/LocalizedStrings/*.lproj -name "Localizable.strings" -type f)

# Resolve any missing languages
for lang in $langs; do
	# https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes
	[[ $lang = "en" ]] && continue  # Skip source language

	alang=${lang/he/iw}  # Hebrew
	alang=${alang/id/in}  # Indonesian
	alang=${alang/zh-Hans/zh}  # Chinese (Simplified)
	alang=${alang/zh-Hant/zh-TW}  # Chinese (Traditional)
	alang=${alang/-/-r}   # Region: e.g. en-rGB
	ls android/app/src/main/res/values-$alang/strings.xml >/dev/null 2>&1 || (echo $alang - Android missing; mkdir -p android/app/src/main/res/values-$alang)

	ilang=$lang
	ls iphone/Maps/LocalizedStrings/$ilang.lproj/Localizable.strings >/dev/null 2>&1 || (echo $ilang - iPhone missing; mkdir -p iphone/Maps/LocalizedStrings/$ilang.lproj)
done
echo -n "Twine: "
echo "$langs" | wc -l
echo -n "Android: "
echo "$android_strings_xml" | wc -l
echo -n "iPhone: "
echo "$iphone_strings" | wc -l

# Perform one last migration from source files
./tools/unix/generate_localizations.sh

# Prepare Android files for Weblate
# Remove Twine header
sed -i "" -E "/^<!-- Android Strings File -->/d" $android_strings_xml
sed -i "" -E "/^<!-- Generated by Twine -->/d" $android_strings_xml
sed -i "" -E "/^<!-- Language: [-a-zA-Z]+ -->/d" $android_strings_xml

# Replace \t indents
sed -i "" -E "s/^	  /        /" $android_strings_xml # Plurals [tab][sp][sp] -> 8x[sp]
sed -i "" -E "s/^	/    /" $android_strings_xml # Other [tab] -> 4x[sp]

# Prepare iPhone files for Weblate
iphone_strings=$(find iphone/Maps/LocalizedStrings/*.lproj -name "Localizable.strings" -type f)
iphone_infoplist_strings=$(find iphone/Maps/LocalizedStrings/*.lproj -name "InfoPlist.strings" -type f)
iphone_stringsdict=$(find iphone/Maps/LocalizedStrings/*.lproj -name "Localizable.stringsdict" -type f)

# Remove Twine headers
sed -i "" 1,6d $iphone_strings $iphone_infoplist_strings # Remove Twine header from .strings
sed -i "" 3,6d $iphone_stringsdict # Remove Twine header from .stringdict

# Remove blank lines between translatable strings
sed -i "" -E '/^$/d' $iphone_strings $iphone_infoplist_strings
# Readd two blank line before header comments
sed -i "" -E '/^[/][*][*]/i \
\
\
' $iphone_strings $iphone_infoplist_strings
# Readd blank line before comments
sed -i "" -E '/^[/][*][^*]/i \
\
' $iphone_strings $iphone_infoplist_strings
# Add a blank line after comment headers
sed -i "" -E $'/^[/][*][*]/,+1{/^"/s/^"/\\\n"/g;}' $iphone_strings $iphone_infoplist_strings
sed -i "" '1,/^./{/^$/d;}' $iphone_strings $iphone_infoplist_strings # Drop spurious first line
